server:
  port: 9191

spring:
  application:
     name: API-GATEWAY


cloud:
  gateway:
    routes:
      - id: PRODUCT-SERVICE
        uri: http://localhost:8080
        predicates:
        - Path=/api/product/**
        filters:
          - name: CircuitBreaker
            args:
               name: PRODUCT-SERVICE
               fallbackuri: forward:/productServiceFallBack
          metadata:
             response-timeout: 40000